# Generated by Django 4.0.4 on 2022-05-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RandomURL',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.TextField()),
                ('hash_val', models.CharField(default=None, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
