# Generated by Django 4.0.4 on 2022-05-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortener', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomurl',
            name='hash_val',
            field=models.CharField(default=None, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='randomurl',
            name='origin',
            field=models.URLField(max_length=2000),
        ),
    ]
